### ISSUE TITLE
Pod structure support?

### ISSUE THREAD

**Issue by angelomachado** [offirgolan/ember-data-mirage#1]
Thank you for your work on this addon.
Do you have any plans to support pods?

**Comment by offirgolan** [comment]
I can try to work on it when I get some more time. This repo will be deprecated soon as this has been merged into ember-cli-mirage so if I continue working on it, it will be directly on that repo.

In terms of support, I dont actually believe that model should exist in the normal pod structure. A lot of times, models are shared / used across different controllers, routes and components which doesnt make sense for them to be part of that structure. I suggest putting all models in `app/models` since they get rolled up to that level anyways.

**Comment by angelomachado** [comment]
Well, that makes a lot of sense. Good to hear that this repo will be merged into mirage. I am closing this issue for now.
